[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "xas_simulator"
version = "0.1.0"
dependencies = [
    "nexpy", "tabulate"
]

[project.entry-points."nexpy.plugins"]
xas_simulator = "xas_simulator:plugin_menu"
